apiVersion: v1
kind: Service
metadata:
  name: service-dogs
  namespace: dogs
  labels: 
    app: dogs
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: dogs