apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dogs
    owner: adriantrucios
  name: dogs
spec:
  replicas: 3
  containers:
  - image: 490085956166.dkr.ecr.us-east-1.amazonaws.com/lab2:dogs_image
    name: dogs
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always